project_name: Example Project
runner_class: JythonRunner

base_params:
    # Random seed based on run_id. The $$ syntax specifies that this value
    # is to be substituted at runtime.
    random.seed: $$run_id$$

    test.variable.1: 123
    test.variable.2: 456
    test.variable.3: xyz
    test.variable.4: abc
    
    output.filename: $$output_path$$test_output_file.txt
    output.filename2: $$output_path$$test_output_file2.txt
    

scenarios:
    - name: Example scenario
      parameters: 

    - name: Example scenario 2
      parameters: 
        test.variable.1: 789

repetitions:
    static_repetitions:
      - test.variable.2: 777

      - test.variable.2: 888

    generators:
      - key: test.variable.3
        generator_type: linear_step
        start: 0
        step_size: 1
        count: 2

      - key: test.variable.4
        generator_type: normal_distribution
        mean: 5
        std_dev: 1
        count: 2