project_name: Example Project
runner_class: RRunner

libraries:
    -  name: R-libraries
       repo_type: svn
       uri: http://rdv-framework.googlecode.com/svn/trunk/R
       revision: 334

base_params:
    test.variable.1: 123
    test.variable.2: 456
    test.variable.3: xyz
    test.variable.4: abc
    path.to.example.script: $$library_path(R-libraries)$$/example.R

    test.output.filename: $$output_path$$test_output_file.txt
    test.output.filename2: $$output_path$$test_output_file2.txt
    

scenarios:
    - name: Example scenario
      parameters:
    - name: Example scenario 2
      parameters:
          test.variable.1: 789

# Note that this file does all repetitions on scen 1, then on scen 2 etc...
# Note that also the original value of the variable is not used.

repetitions:
    static_repetitions:
      - test.variable.2: 777

      - test.variable.2: 888

    generators:
      - key: test.variable.3
        generator_type: linear_step
        start: 0
        step_size: 1
        count: 2

      - key: test.variable.4
        generator_type: normal_distribution
        mean: 5
        std_dev: 1
        count: 2
